translate tutorial/part one
gatsbyjs/gatsby-fr pull request #11
Opened 2019-11-03 20:36 UTC by SamuelAlev

2019-11-04 22:39 UTC, dantereve requested changes
Good job 🥳 ! I've just spotted some typos and did some suggestions to fix them.

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +## Utilisation des starters Gatsby
Not translating starter is a great idea!

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +Dans votre éditeur, ouvrez le code généré pour votre site “Hello World” et prenez connaissance des différents répertoires et fichiers contenu dans le projet ‘hello-world’. Ça devrait ressembler a que
```suggestion
Dans votre éditeur, ouvrez le code généré pour votre site “Hello World” et prenez connaissance des différents répertoires et fichiers contenus dans le projet ‘hello-world’. Ça devrait ressembler à quelque chose comme ça :
```

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +> 💡 Gatsby utilise le **rechargement immédiat** pour accélerer votre processus de développement. Lorsque vous exécutez un serveur de développement Gatsby, les fichiers du site Gatsby sont “surveillés
```suggestion
> 💡 Gatsby utilise le **rechargement immédiat** pour accélérer votre processus de développement. Lorsque vous exécutez un serveur de développement Gatsby, les fichiers du site Gatsby sont “surveillés” en arrière-plan - chaque fois que vous enregistrez un fichier, vos modifications sont immédiatement reflétées dans le navigateur. Vous n'avez pas besoin d'actualiser la page ou de redémarrer le serveur de développement, vos modifications apparaissent.
```

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +_Si vous êtes familier avec React et JSX, n'hésitez pas alors à passer cette section.._ Si vous n’avez jamais utilisé le framework React auparavant, vous vous demandez peut-être ce que HTML fait dans
```suggestion
_Si vous êtes familier avec React et JSX, n'hésitez pas alors à passer cette section.._ Si vous n’avez jamais utilisé le framework React auparavant, vous vous demandez peut-être ce que HTML fait dans une fonction JavaScript. Ou pourquoi nous importons `react` sur la première ligne, mais ne l’utilisons apparemment pas nulle part. Cette façon hybride «HTML-in-JS» est en fait une extension de syntaxe de JavaScript pour React, appelée JSX. Vous pouvez suivre ce tutoriel sans expérience préalable de React, mais si vous êtes curieux, voici un bref aperçu…
```

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +Vous pouvez maintenant voir l’utilisation de l’importation `'react'`! Mais attendez. Vous écrivez en JSX, et non pas en HTML pur et en JavaScript. Comment le navigateur lit-il cela? La réponse courte
```suggestion
Vous pouvez maintenant voir l’utilisation de l’import `'react'`! Mais attendez. Vous écrivez en JSX, et non pas en HTML pur et en JavaScript. Comment le navigateur lit-il cela? La réponse courte: ce n’est pas le cas. Les sites Gatsby sont fournis avec des outils déjà configurés pour convertir votre code source en quelque chose que les navigateurs peuvent interpréter.
```

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +Le component Gatsby `<Link />` permet de lier différentes pages de votre site. Pour les liens externes non géré par votre site Gatsby, utilisez la balise HTML par défaut `<a>`.
```suggestion
Le composant Gatsby `<Link />` permet de lier différentes pages de votre site. Pour les liens externes non gérés par votre site Gatsby, utilisez la balise HTML par défaut `<a>`.
```

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +- Avez appris sur les générateurs de Gatsby, et comment les utiliser pour créer des nouveaux projets
```suggestion
- Avez découvert les starters de Gatsby, et comment les utiliser pour créer des nouveaux projets
```

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +- Avez appris sur la syntaxe de JSX
```suggestion
- Avez découvert la syntaxe de JSX
```

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +- Avez appris sur les composants
```suggestion
- Avez découvert les composants
```

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +- Avez appris sur les composants et sous-composants de pages Gatsby
```suggestion
- Avez découvert les composants et sous-composants de pages Gatsby
```

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +- Avez appris sur les “props” React et la réutilisation de composants React
```suggestion
- Avez découvert les “props” React et la réutilisation de composants React
```

2019-11-04 22:39 UTC, dantereve commented on docs/tutorial/part-one/index.md
> +Maintenant, continuez avec [**ajouter du styles à votre site**](/tutorial/part-two/)!
```suggestion
Maintenant, continuez avec [**ajouter des styles à votre site**](/tutorial/part-two/)!
```

2019-11-05 08:22 UTC, SamuelAlev commented
Thank you for your feedback !
I fixed the typos.

2019-11-05 09:11 UTC, dantereve approved these changes

2019-11-05 09:11 UTC, merged