recipes.md file translation
gatsbyjs/gatsby-fr pull request #16
Opened 2019-12-03 13:54 UTC by benoitcalin

I did my best with this fat one, happy to read your comments!

2019-12-04 20:40 UTC, dantereve requested changes
That was a pretty long one mmh? 😱You know what? You just did an AWESOME work with this one. This is your first PR to Gatsby but man, what a PR!  Thank you! 🥳
I've spotted some little things I would like you to change (really minor things). If it's ok for you, you can commit those changes directly from this PR.

2019-12-04 20:40 UTC, dantereve commented on docs/docs/recipes.md
> +Une ou deux phrases à propos du sujet. Le plus concis et concentré, le mieux !
```suggestion
Une ou deux phrases à propos du sujet. Plus cela est concis et ciblé, meilleur c'est !
```

2019-12-04 20:40 UTC, dantereve commented on docs/docs/recipes.md
> +- `gatsby-ssr.js` — utilisez les API de rendu côté serveur de Gatsby pour personnaliser les paramètres par défaut affectant le rendu côté serveur
```suggestion
- `gatsby-ssr.js` — utiliser les API de rendu côté serveur de Gatsby pour personnaliser les paramètres par défaut affectant le rendu côté serveur
```

2019-12-04 20:40 UTC, dantereve commented on docs/docs/recipes.md
> +1. Ouvrez le composant page `index.js` (`src/pages/index.js`), importez le composant `<Link />` de Gatsby, ajoutez un composant `<Link />`  au-dessus de l'en-tête, et donnez-lui une propriété `to` av
```suggestion
1. Ouvrez le composant page `index.js` (`src/pages/index.js`), importez le composant `<Link />` de Gatsby, ajoutez un composant `<Link />`  au-dessus de l'en-tête, et donnez-lui une propriété `to` avec la valeur de `"/contact/"` pour le chemin :
```

2019-12-04 20:40 UTC, dantereve commented on docs/docs/recipes.md
> +- Ajouter du stylisme avec [Composants Layout](/docs/layout-components/)
```suggestion
- Ajouter du style avec les [Composants de Mise en Page](/docs/layout-components/)
```

2019-12-04 20:40 UTC, dantereve commented on docs/docs/recipes.md
> +1. Le composant `StaticQuery` nécessite deux outils de rendu : `query` et `render`
```suggestion
1. Le composant `StaticQuery` nécessite deux props de rendu : `query` et `render`
```

2019-12-04 20:40 UTC, dantereve commented on docs/docs/recipes.md
> +Depuis Gatsby v2.1.0, vous pouvez utiliser le hook `useStaticQuery` pour interroger des données avec une fonction JavaScript au lieu d'un composant. La syntaxe élimine la nécessité d'un composant `<S
```suggestion
Depuis Gatsby v2.1.0, vous pouvez utiliser le hook `useStaticQuery` pour interroger des données avec une fonction JavaScript au lieu d'un composant. La syntaxe élimine la nécessité d'un composant `<StaticQuery>` enveloppant tout, ce que certaines personnes trouvent plus simple à écrire.
```

2019-12-05 09:07 UTC, benoitcalin commented
My pleasure Mathias, I committed your changes.
Reading all these recipes gave me a better understanding on some Gatsby functionalities, so it's a win/win ;)

2019-12-05 09:09 UTC, dantereve approved these changes

2019-12-05 09:12 UTC, dantereve commented
And it's a wrap! Glad you enjoyed it. If you want to translate some other page feel free to do so. It's seems that all current pages are taken but very soon much more will be available 😉.

2019-12-05 09:12 UTC, merged