Translation of tutorial/part-zero.md
gatsbyjs/gatsby-fr pull request #22
Opened 2019-12-28 15:28 UTC by alexislepresle

Translation of tutorial/part-zero.md to french

2019-12-29 10:30 UTC, dantereve requested changes
Great work! I've found some minor typos to fix before merging. You can accept them directly from this PR. Thanks 👍.

2019-12-29 10:30 UTC, dantereve commented on docs/tutorial/part-zero/index.md
> +- Une fois que vous avez identifié le package souhaité, vous pouvez utiliser la CLI npm pour l'installer dans votre projet ou globalement (comme les autres outils CLI). La CLI npm est ce qui parle au
```suggestion
- Une fois que vous avez identifié le package souhaité, vous pouvez utiliser la CLI npm pour l'installer dans votre projet ou globalement (comme les autres outils CLI). La CLI npm est ce qui parle au registre.
```

2019-12-29 10:30 UTC, dantereve commented on docs/tutorial/part-zero/index.md
> +- Exécutez le serveur de développement Gatsby et visité votre site localement
```suggestion
- Exécutez le serveur de développement Gatsby et visitez votre site localement
```

2019-12-29 10:30 UTC, dantereve commented on docs/tutorial/part-zero/index.md
> +Avant de commencer à créer votre premier site Gatsby, vous devez vous familiariser avec certaines technologies Web de base et vous assurer que vous avez installé tous les outils logiciels requis.
```suggestion
Avant de commencer à créer votre premier site Gatsby, vous devez vous familiariser avec certaines technologies web de base et vous assurer que vous avez installé tous les outils logiciels requis.
```

2019-12-29 10:30 UTC, dantereve commented on docs/tutorial/part-zero/index.md
> +La ligne de commande (CLI) est une interface textuelle utilisée pour exécuter des commandes sur votre ordinateur. Vous le verrez également souvent sous le nom de terminal. Dans ce didacticiel, nous u
```suggestion
La ligne de commande est une interface textuelle utilisée pour exécuter des commandes sur votre ordinateur. Vous le verrez également souvent sous le nom de terminal. Dans ce didacticiel, nous utiliserons les deux de manière interchangeable. C'est un peu comme utiliser le Finder sur un Mac ou l'Explorateur sur Windows. Finder et Explorer sont des exemples d'interfaces utilisateur graphiques (GUI). La ligne de commande est un moyen puissant et textuel d'interagir avec votre ordinateur.
```

2019-12-29 10:30 UTC, dantereve commented on docs/tutorial/part-zero/index.md
> +Prenez un temps pour trouver et ouvrir l'interface de ligne de commande (CLI) de votre ordinateur. Selon le système d'exploitation que vous utilisez, voir [**instructions pour Mac**](http://www.macwo
```suggestion
Prenez le temps pour trouver et ouvrir l'interface de ligne de commande (CLI) de votre ordinateur. Selon le système d'exploitation que vous utilisez, voir [**instructions pour Mac**](http://www.macworld.co.uk/feature/mac-software/how-use-terminal-on-mac-3608274/), [**instructions pour Windows**](https://www.quora.com/How-do-I-open-terminal-in-windows) ou [**instructions pour Linux**](https://www.howtogeek.com/140679/beginner-geek-how-to-start-using-the-linux-terminal/).
```

2019-12-29 10:30 UTC, dantereve commented on docs/tutorial/part-zero/index.md
> +Pour installer Gatsby et Node.js, il est recommandé d'utiliser [Homebrew](https://brew.sh/). Une petite configuration au début peut vous éviter quelques maux de tête plus tard!
```suggestion
Pour installer Gatsby et Node.js, il est recommandé d'utiliser [Homebrew](https://brew.sh/). Une petite configuration au début peut vous éviter quelques maux de tête plus tard !
```

2019-12-29 10:30 UTC, dantereve commented on docs/tutorial/part-zero/index.md
> +- Téléchargé un éditeur de code
```suggestion
- Téléchargez un éditeur de code
```

2019-12-29 10:58 UTC, alexislepresle commented
> Great work! I've found some minor typos to fix before merging. You can accept them directly from this PR. Thanks 👍.

Thanks Mathias 👍

2019-12-30 08:43 UTC, dantereve approved these changes

2019-12-30 08:43 UTC, merged