Part seven
gatsbyjs/gatsby-fr pull request #25
Opened 2020-01-27 06:20 UTC by sheplu

Hello !

Un peu (beaucoup) de retard, mais voila la partie 7

J'attends vos retours

2020-01-31 16:20 UTC, mindsers requested changes
Thanks for you PR ❤️ 

This is not a full review but we can go step by step

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +> Ce tutoriel est inclu dans la série sur les niveau de données de Gatsby. Soyez sur d'avoir lu [part 4](/tutorial/part-four/), [part 5](/tutorial/part-five/), et [part 6](/tutorial/part-six/) avant
```suggestion
> Ce tutoriel est inclu dans la série sur les couches de données de Gatsby. Soyez sur d'avoir lu [la partie 4](/tutorial/part-four/), [la partie 5](/tutorial/part-five/), et [la partie 6](/tutorial/part-six/) avant de continuer ici.
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +les extraits mais les pages complètes pour les fichiers markdown.
```suggestion
les extraits mais des pages complètes pour chacun de vos fichiers markdown.
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +allez maintenant apprendre comment _programmatiquement_ créer des pages depuis _data_. Gatsby _n'est_ pas
```suggestion
allez maintenant apprendre comment _programmatiquement_ créer des pages à partir de _données_. Gatsby _n'est_ pas
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +limité à concevoir des pages depuis des fichiers comme beaucoup de générateurs de sites statiques. Gatsby vous permet d'utiliser GraphQL pour rechercher vos _données_ et _mapper_ le résultat en _page
```suggestion
limité à concevoir des pages depuis des fichiers comme beaucoup de générateurs de sites statiques. Gatsby vous permet d'utiliser GraphQL pour rechercher vos _données_ et _transformer_ le résultat en _pages_ - tout cela au moment du build. C'est réellement une idée puissante. Vous allez explorer ces implications et les façons de s'en servir sur la suite de ce tutoriel.
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +limité à concevoir des pages depuis des fichiers comme beaucoup de générateurs de sites statiques. Gatsby vous permet d'utiliser GraphQL pour rechercher vos _données_ et _mapper_ le résultat en _page
I'm not comfortable with "rechercher vos données". It's like you don't find you data and gatsby give you tools to investigate.

I don't know how to say it better though

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +Commencons
```suggestion
Commençons.
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +Créer de nouvelles pages nécessite deux étapes:
There is a space before colon in French.
```suggestion
Créer de nouvelles pages nécessite deux étapes :
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +Ces deux APIs sont utilisées dans de nombreux sites et plugins
```suggestion
Ces deux APIs sont utilisées dans de nombreux sites et plugins.
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +Pour créer vos pages markdown vous allez apprendre à utiliser deux APIs de Gatsby:
```suggestion
Pour créer vos pages markdown vous allez apprendre à utiliser deux APIs de Gatsby :
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +Nous nous efforçons de faire les APIs de Gatsby simple à implementer. Pour implémenter une API vous devez exporter la fonction avec le nom de l'API depuis `gatsby-node.js`.
```suggestion
Nous nous efforçons de rendre les APIs de Gatsby simple à implementer. Pour implémenter une API vous devez exporter une fonction avec le nom de l'API depuis `gatsby-node.js`.
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +Changez la fonction pour qu'elle affiche  maintenant seulement les noeuds `MarkdownRemark`.
```suggestion
Changez la fonction pour qu'elle affiche maintenant seulement les nœuds `MarkdownRemark`.
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +Eteignez et relancez le serveur de développement. En le faisant, vous allez voir de nouveaux noeuds créés être affiché dans la console du terminale
```suggestion
Eteignez et relancez le serveur de développement. En le faisant, vous allez voir de nouveaux nœuds créés être affiché dans la console du terminale
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +Vous voulez utiliser chaque nom de fichier markdown pour créer le slug de la page. Donc `pandas-et-bananes.md` va devenir `/pandas-et-bananes/`. Mais comment obtenir le nom du fichier depuis le noeud
```suggestion
Vous voulez utiliser chaque nom de fichier markdown pour créer le slug de la page. Donc `pandas-et-bananes.md` va devenir `/pandas-et-bananes/`. Mais comment obtenir le nom du fichier depuis le nœud `MarkdownRemark` ? Pour y accéder vous devez _traverser_ le "graph de nœud" jusqu'à son nœud _parent_ `File`, puisque les nœuds `File` contiennent les données dont vous avez besoin sur les fichiers sur le disque. Pour cela, modifiez votre fonction encore une fois :
```

2020-01-31 16:20 UTC, mindsers commented on docs/tutorial/part-seven/index.md
> +Après avoir relancé votre serveur de développement vous devriez voir affiche sur l'écran du terminal les chemins relatifs pour vos deux fichiers markdown
```suggestion
Après avoir relancé votre serveur de développement vous devriez voir sur l'écran du terminal les chemins relatifs pour vos deux fichiers markdown.
```

2020-04-19 10:06 UTC, dantereve commented
As we still have l no news from you I'm closing this PR so that someone can take over your translation and update it with recent changes in the main repo. As it's one of your private branches we can't modify this ourselves. Please feel free to take another page or even update this one 👌

2020-04-19 10:06 UTC, closed without merging