Translated browser-apis.md
gatsbyjs/gatsby-fr pull request #38
Opened 2020-03-09 17:12 UTC by Prabhu646

Addresses #1

2020-03-10 01:00 UTC, mindsers requested changes
Thank you for your contribution! It is really appreciated.  ❤️ 🎉 

There are some stuffs we want to talk about before merging your code. 🚀

2020-03-10 01:00 UTC, mindsers commented on docs/docs/browser-apis.md
> +description: Documentation sur l'utilisation des API de navigateur standard dans Gatsby
Is it the browser that is standard? Or the APIs?

```suggestion
description: Documentation sur l'utilisation des APIs standards de navigateur dans Gatsby
```

2020-03-10 01:00 UTC, mindsers commented on docs/docs/browser-apis.md
> +Implémentez toute de ces API en les exportant à partir d'un fichier nommé `gatsby-browser.js` dans la racine de votre projet.
```suggestion
Implémentez l'une de ces APIs en les exportant à partir d'un fichier nommé `gatsby-browser.js` à la racine de votre projet.
```

2020-03-10 04:04 UTC, Prabhu646 commented on docs/docs/browser-apis.md
> +description: Documentation sur l'utilisation des API de navigateur standard dans Gatsby
Right! Making the changes.

2020-03-10 04:08 UTC, Prabhu646 commented
Made those changes

2020-03-12 23:03 UTC, dantereve approved these changes
Thanks for your help, looks good to me! 

It looks like it's your very first contribution to Gatsby, good job!  🚀If you want to take some other page to translate when you have some time, feel free to do so 😅.

2020-03-13 06:13 UTC, Prabhu646 commented
@dantereve Thankyou! Will surely do

2020-03-13 07:35 UTC, mindsers approved these changes

2020-03-13 07:36 UTC, merged