Translated docs/actions.md
gatsbyjs/gatsby-fr pull request #48
Opened 2020-06-19 18:29 UTC by gauravgupta45

Completed the translation of `docs/actions.md`. Merge it once you're satisfied :)

2020-06-19 18:33 UTC, SamuelAlev requested changes
Please **do not** translate the keys.

2020-06-19 18:44 UTC, gauravgupta45 commented
Is that fine now?

2020-06-19 19:12 UTC, gauravgupta45 commented
Check if it is fine now.

2020-06-20 09:13 UTC, SamuelAlev requested changes

2020-06-20 09:13 UTC, SamuelAlev commented on docs/docs/actions.md
> +contentsHeading: les fonctions
```suggestion
contentsHeading: Les fonctions
```

2020-06-20 09:18 UTC, SamuelAlev approved these changes

2020-06-20 09:18 UTC, merged