Translate docs/node-model.md
gatsbyjs/gatsby-fr pull request #50
Opened 2020-06-21 10:51 UTC by gauravgupta45

[Translation](https://github.com/gatsbyjs/gatsby-fr/issues/1#issuecomment-647109611) for `docs/node-model.md`.

2020-06-24 07:40 UTC, mindsers requested changes
Hi! Thanks for your time contributing to this project! ❤️ 

This is a great translation. Can you also translate the code blocks? 
Please refer to https://github.com/gatsbyjs/gatsby-fr/blob/master/style-guide.md#text-in-code-blocks

2020-06-24 08:22 UTC, gauravgupta45 commented
Please let me know if something's wrong.

2020-06-25 20:13 UTC, SamuelAlev submitted a review, later dismissed

2020-06-25 20:13 UTC, SamuelAlev commented on docs/docs/node-model.md
> +  Requete: {
```suggestion
  Query: {
```
I think this need to stay in English. 
Someone to confirm?

2020-06-26 06:07 UTC, gatarelib submitted a review, later dismissed

2020-06-26 06:23 UTC, mindsers approved these changes

2020-06-26 06:24 UTC, merged