Translate api-files-gatsby-node.md
gatsbyjs/gatsby-fr pull request #54
Opened 2020-07-28 17:49 UTC by noisefilter19

Addresses #1

2020-07-29 05:46 UTC, mindsers submitted a review, later dismissed
Thank you for taking time to contribute!! ❤️ 

I only have one request before merging.

2020-07-29 05:46 UTC, mindsers commented on docs/docs/api-files-gatsby-node.md
> +Le code du fichier `gatsby-node.js` est exécuté une fois dans le processus de création de votre site. Vous pouvez l'utiliser pour créer des pages de manière dynamique, ajouter des nœuds dans GraphQL
```suggestion
Le code du fichier `gatsby-node.js` est exécuté une fois dans le processus de création de votre site. Vous pouvez l'utiliser pour créer des pages de manière dynamique, ajouter des nœuds dans GraphQL ou répondre à des événements pendant le cycle de vie de la construction. Pour utiliser les [APIs Gatsby Node] (/docs/node-apis/), créez un fichier nommé `gatsby-node.js` à la racine de votre site. Exportez l'une des API que vous souhaitez utiliser dans ce fichier.
```

2020-07-29 05:53 UTC, noisefilter19 commented
Done :)

2020-07-30 19:59 UTC, SamuelAlev requested changes

2020-07-30 19:59 UTC, SamuelAlev commented on docs/docs/api-files-gatsby-node.md
> +Le code du fichier `gatsby-node.js` est exécuté une fois dans le processus de création de votre site. Vous pouvez l'utiliser pour créer des pages de manière dynamique, ajouter des nœuds dans GraphQL
```suggestion
Le code du fichier `gatsby-node.js` est exécuté une fois dans le processus de création de votre site. Vous pouvez l'utiliser pour créer des pages de manière dynamique, ajouter des nœuds dans GraphQL ou répondre à des événements pendant le cycle de vie de la construction. Pour utiliser les [APIs Gatsby Node](/docs/node-apis/), créez un fichier nommé `gatsby-node.js` à la racine de votre site. Exportez l'une des API que vous souhaitez utiliser dans ce fichier.
```

Petit espace en trop

2020-07-30 19:59 UTC, SamuelAlev commented on docs/docs/api-files-gatsby-node.md
> +Chaque API Gatsby Node transmet un [ensemble d'assistants API Node] (/docs/node-api-helpers/). Ceux-ci vous permettent d'accéder à plusieurs méthodes telles que la rapport ou d'effectuer des actions
```suggestion
Chaque API Gatsby Node transmet un [ensemble d'assistants API Node](/docs/node-api-helpers/). Ceux-ci vous permettent d'accéder à plusieurs méthodes telles que rapporter ou d'effectuer des actions telles que la création de nouvelles pages.
```

"rapporter" ou laisser "reporting" mais définitivement pas "la rapport"

2020-07-30 20:04 UTC, noisefilter19 commented
Thankyou for the suggestions. Have committed them

2020-07-30 20:34 UTC, SamuelAlev approved these changes

2020-07-30 22:41 UTC, merged