Translate api-files-gatsby-ssr.md
gatsbyjs/gatsby-fr pull request #56
Opened 2020-07-31 04:07 UTC by noisefilter19

Addresses #1

2020-07-31 10:32 UTC, SamuelAlev requested changes
Salut,
Merci pour ta PR.
Par contre, merci de **NE PAS** passer le fichier en entier dans un outil de traduction, il en retourne plus d'erreurs.

2020-07-31 10:32 UTC, SamuelAlev commented on docs/docs/api-files-gatsby-ssr.md
> +Le fichier `gatsby-ssr.js` vous permet de modifier le contenu des fichiers HTML statiques car ils sont côté serveur rendus (SSR) par Gatsby et Node.js. Pour utiliser les [API Gatsby SSR](/docs/ssr-ap
```suggestion
Le fichier `gatsby-ssr.js` vous permet de modifier le contenu des fichiers HTML statiques car ils sont rendus côté serveur (SSR) par Gatsby et Node.js. Pour utiliser les [APIs Gatsby SSR](/docs/ssr-apis/), créez un fichier appelé `gatsby-ssr.js` à la racine de votre site. Exportez l'une des APIs que vous souhaitez utiliser dans ce fichier.
```

2020-07-31 10:32 UTC, SamuelAlev commented on docs/docs/api-files-gatsby-ssr.md
> +Les API `wrapPageElement` et `wrapRootElement` existent à la fois dans le SSR et [browser API] (/docs/browser-apis). Si vous utilisez un d'entre eux, demandez-vous si vous devez l'implémenter à la fo
```suggestion
Les APIs `wrapPageElement` et `wrapRootElement` existent à la fois dans le SSR et dans les [APIs des navigateurs](/docs/browser-apis). Si vous en utilisez une, demandez-vous si vous devez l'implémenter à la fois dans `gatsby-ssr.js` et `gatsby-browser.js` afin que les pages générées à travers SSR avec Node.js soient les mêmes après avoir été [hydratées](/docs/glossary#hydration) par le moteur JavaScript.
```

2020-07-31 10:32 UTC, SamuelAlev commented on docs/docs/api-files-gatsby-ssr.md
>  title: The gatsby-ssr.js API file
```suggestion
title: Le fichier API gatsby-ssr.js
```

2020-07-31 12:09 UTC, noisefilter19 commented
@SamuelAlev Sorry. Made the corrections. Thankyou for that

2020-08-01 09:39 UTC, SamuelAlev approved these changes

2020-08-01 09:39 UTC, merged