French api-specification.md
gatsbyjs/gatsby-fr pull request #59
Opened 2020-08-17 18:00 UTC by Lavish-Garg

2020-08-19 21:27 UTC, dantereve requested changes, later dismissed
Hi! Thanks for your help! Pretty nice first PR! 👌 I've made some suggestions, can you commit them so that I can approve your PR to be merged?

2020-08-19 21:27 UTC, dantereve commented on docs/docs/api-specification.md
> +Les API de Gatsby sont conçues conceptuellement dans une certaine mesure après React.js pour améliorer la cohérence entre les deux systèmes.
```suggestion
Les API de Gatsby sont conçues conceptuellement dans une certaine mesure d'après React.js pour améliorer la cohérence entre les deux systèmes.
```

2020-08-19 21:27 UTC, dantereve commented on docs/docs/api-specification.md
> +- Création de pages (par exemple, un répertoire de fichiers markdown est tous transformé en pages avec des URL dérivées de leurs noms de fichiers).
```suggestion
- Création de pages (par exemple, un répertoire de fichiers markdown qui est intégralement transformé en pages avec des URL dérivées de leurs noms de fichiers).
```

2020-08-19 21:27 UTC, dantereve commented on docs/docs/api-specification.md
> +Les plugins peuvent également dépendre d'autres plugins. [The Sharp plugin](/packages/gatsby-plugin-sharp/) expose un certain nombre d'API de haut niveau pour transformer des images que plusieurs aut
```suggestion
Les plugins peuvent également dépendre d'autres plugins. [The Sharp plugin](/packages/gatsby-plugin-sharp/) expose un certain nombre d'API de haut niveau pour transformer des images dont d'autres plugins dépendent. [gatsby-transformer-remark](/packages/gatsby-transformer-remark/) effectue une transformation basique markdown-> html mais expose une API permettant à d'autres plugins d'intervenir dans le processus de conversion, par ex. [gatsby-remark-prismjs](/packages/gatsby-remark-prismjs/) ce qui ajoute une coloration syntaxique aux blocs de code.
```

2020-08-19 21:27 UTC, dantereve commented on docs/docs/api-specification.md
> +Les plugins Transformer sont découplés des plugins source. Les plugins Transformer examinent le type de média des nouveaux nœuds créés par les plugins source pour décider s'ils peuvent le transformer
```suggestion
Les plugins Transformer sont découplés des plugins source. Les plugins Transformer examinent le type de média des nouveaux nœuds créés par les plugins source pour décider s'ils peuvent le transformer ou non. Ce qui signifie qu'un plugin transformer markdown peut transformer le markdown de n'importe quelle source sans aucune autre configuration, par exemple à partir d'un fichier, d'un commentaire de code ou d'un service externe comme Trello qui prend en charge le markdown dans certains de ses champs de données.
```

2020-08-19 21:27 UTC, dantereve commented on docs/docs/api-specification.md
> +Le processus d'amorçage est le suivant:
```suggestion
Le processus de bootstrap est le suivant:
```

2020-08-20 13:49 UTC, SamuelAlev requested changes
Peux-tu également traduire les différents liens ? :)

2020-08-21 06:27 UTC, Lavish-Garg commented
> 
> 
> Peux-tu également traduire les différents liens ? :)



> 
> 
> Peux-tu également traduire les différents liens ? :)

ohk je vais le faire

2020-08-22 19:18 UTC, SamuelAlev requested changes

2020-08-22 19:18 UTC, SamuelAlev commented on docs/docs/api-specification.md
> +Les trois principales inspirations pour cette API et cette spécification sont l'API de React.js spécifiquement [Courriel de @ leebyron sur l'API React](https://gist.github.com/vjeux/f2b015d230cc1ab18
```suggestion
Les trois principales inspirations pour cette API et cette spécification sont l'API de React.js spécifiquement [Mail de @leebyron sur l'API React](https://gist.github.com/vjeux/f2b015d230cc1ab18ed1df30550495ed), ce discours ["How to Design a Good API and Why it Matters" par Joshua Bloch](https://www.youtube.com/watch?v=heh4OeB9A-c&app=desktop) qui a conçu de nombreuses parties de Java, et [Hapi.js](https://hapijs.com/api)' conception de plugin.
```

2020-08-22 19:18 UTC, SamuelAlev commented on docs/docs/api-specification.md
> +A chaque point d'extension, Gatsby identifie les plugins qui implémentent l'API et les appelle en série en suivant leur ordre dans le site `gatsby-config.js`.
```suggestion
A chaque point d'extension, Gatsby identifie les plugins qui implémentent l'API et les appelle en série en suivant leur ordre dans le fichier de configuration `gatsby-config.js`.
```

2020-08-22 19:18 UTC, SamuelAlev commented on docs/docs/api-specification.md
> +charger la configuration du site -> charger des plugins -> nœuds source -> transformer les nœuds -> créer un schéma graphql -> créer des pages -> compiler des requêtes de composants -> exécuter des r
```suggestion
charger la configuration du site -> charger les plugins -> nœuds source -> transformer les nœuds -> créer un schéma graphql -> créer des pages -> compiler des requêtes de composants -> exécuter des requêtes -> fin
```

2020-08-22 19:18 UTC, SamuelAlev commented on docs/docs/api-specification.md
> +Gatsby a plusieurs processus. Le plus important est le processus de "bootstrap". Il comporte plusieurs sous-processus. Une partie délicate de leur conception est qu'ils s'exécutent une fois pendant l
```suggestion
Gatsby a plusieurs processus. Le plus important est le processus de "bootstrap". Il comporte plusieurs sous-processus. Une partie délicate de leur conception est qu'ils s'exécutent une fois pendant le bootstrap initial, mais restent également en vie pendant le développement pour continuer à répondre aux changements. C'est ce qui pousse au rechargement à chaud que toutes les données Gatsby sont "vivantes" et réagissent aux changements de l'environnement.
```

2020-08-22 19:18 UTC, SamuelAlev commented on docs/docs/api-specification.md
> +Si vous ne connaissez pas le cycle de vie de Gatsby, consultez la présentation [API Gatsby Lifecycle](/docs/gatsby-lifecycle-apis/).
```suggestion
Si vous ne connaissez pas le cycle de vie de Gatsby, consultez la présentation [Cycle de vie de l'API Gatsby](/docs/gatsby-lifecycle-apis/).
```

2020-08-23 07:23 UTC, Lavish-Garg commented
terminé

2020-08-25 18:25 UTC, SamuelAlev requested changes
Petits derniers détails

2020-08-25 18:25 UTC, SamuelAlev commented on docs/docs/api-specification.md
> +- _Component extensions_ —  extensions qui peuvent être résolues en tant que composants. `.js` et `.jsx` sont pris en charge par core. Mais les plugins peuvent ajouter la prise en charge d'autres lan
```suggestion
- _Component extensions_ — extensions qui peuvent être résolues en tant que composants. `.js` et `.jsx` sont pris en charge par core. Mais les plugins peuvent ajouter la prise en charge d'autres langages de compilation en js.
```

2020-08-25 18:25 UTC, SamuelAlev commented on docs/docs/api-specification.md
> +- _Page Component_ - Composant React.js qui rend une page et peut éventuellement spécifier une requête GraphQL
```suggestion
- _Page Component_ — Composant React.js qui rend une page et peut éventuellement spécifier une requête GraphQL
```

2020-08-25 18:25 UTC, SamuelAlev commented on docs/docs/api-specification.md
> +- _Page_ - une page de site avec un chemin, un composant de modèle et une requête GraphQL facultative.
```suggestion
- _Page_ — une page de site avec un chemin, un composant de modèle et une requête GraphQL facultative.
```

2020-08-25 18:26 UTC, SamuelAlev approved these changes

2020-08-25 18:27 UTC, merged