Translating docs/docs/recipes/querying-data.md
gatsbyjs/gatsby-fr pull request #63
Opened 2020-10-04 18:01 UTC by rnd-debug

2020-10-10 06:12 UTC, rnd-debug commented
If the PR is accepted, would it be possible to tag it with `hacktoberfest-accepted`? 😇 They have updated their policy in order to reduce spam PRs ([DigitalOcean link](https://hacktoberfest.digitalocean.com/hacktoberfest-update))

2020-10-14 06:21 UTC, dantereve requested changes, later dismissed
Hello! Thanks for your help, that was a big one 😅. I've requested minor changes and I have asked an open question concerning "étiquette graphql" that we can discuss further.

2020-10-14 06:21 UTC, dantereve commented on docs/docs/recipes/querying-data.md
> +Vous pouvez utiliser l'étiquette `graphql` pour récupérer des données dans les pages de votre site Gatsby. Cela vous permet d'avoir accès à tout ce qui est inclus dans la couche de données Gatsby (pa
I'm not convinced by "étiquette `graphql`". Can't we still use "tag" here? I've never heard someone talking about some "étiquettes graphql".

2020-10-14 06:21 UTC, dantereve commented on docs/docs/recipes/querying-data.md
> +        Titre récupéré par le composant non-page via une StaticQuery:
```suggestion
        Titre récupéré par NonPageComponent via une StaticQuery :
```
C'est le nom du composant pas besoin de le traduire ici 😉

2020-10-14 06:21 UTC, dantereve commented on docs/docs/recipes/querying-data.md
> +- Plus sur [l'utilisation de StaticQuery dans les composants pour récupérer les données](/docs/static-query/)
```suggestion
- [Plus sur l'utilisation de StaticQuery dans les composants pour récupérer les données](/docs/static-query/)
```

2020-10-14 08:01 UTC, rnd-debug commented on docs/docs/recipes/querying-data.md
> +Vous pouvez utiliser l'étiquette `graphql` pour récupérer des données dans les pages de votre site Gatsby. Cela vous permet d'avoir accès à tout ce qui est inclus dans la couche de données Gatsby (pa
Fixed. I wasn't confortable with "étiquette" either.

2020-10-14 08:02 UTC, rnd-debug commented on docs/docs/recipes/querying-data.md
> +        Titre récupéré par le composant non-page via une StaticQuery:
Updated: première mention => "composants NonPageComponent" .Dans la suite, j'utilise uniquement "NonPageComponent" sans le "composant".

2020-10-30 08:50 UTC, mindsers commented on docs/docs/recipes/querying-data.md
> +Vous pouvez utiliser l'étiquette `graphql` pour récupérer des données dans les pages de votre site Gatsby. Cela vous permet d'avoir accès à tout ce qui est inclus dans la couche de données Gatsby (pa
However it seems to be "étiquette" in [other documentations](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Littéraux_gabarits#Gabarits_étiquetés). Maybe we can use the suggestion in https://github.com/gatsbyjs/gatsby-fr/issues/6#issuecomment-716088892 if it helps to understand.

2020-10-30 15:03 UTC, rnd-debug commented on docs/docs/recipes/querying-data.md
> +Vous pouvez utiliser l'étiquette `graphql` pour récupérer des données dans les pages de votre site Gatsby. Cela vous permet d'avoir accès à tout ce qui est inclus dans la couche de données Gatsby (pa
Je pense que "étiquette" serait plus "approprié" à un utilisateur [québécois](https://www.btb.termiumplus.gc.ca/publications/media-soc-fra.html), là où l'utilisateur français lambda trouverait ça louche.
J'aime bien la suggestion => updated.

2020-10-30 17:19 UTC, mindsers approved these changes
A new PR merged! Thanks again for your help! 🚀 ❤️

2020-10-30 17:20 UTC, merged

2022-12-19 17:47 UTC, maa786 commented
Perfect translation for my testes. Let’s merge this!