translating tutorial/part-seven/index.md
gatsbyjs/gatsby-fr pull request #64
Opened 2020-10-10 16:35 UTC by rnd-debug

2020-10-14 06:34 UTC, dantereve requested changes, later dismissed
Another big page for you 🔥. Thanks for your help and rest assured that I will label your PRs with `hacktoberfest-accepted`. Hope you had fun in the process.

I've requested a microscopic change. Once this is done, let's merged this.

![](https://media.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif)

2020-10-14 06:34 UTC, dantereve commented on docs/tutorial/part-seven/index.md
> +1.  Récupèrer les données avec GraphQL
```suggestion
1.  Récupérer les données avec GraphQL
```

2020-10-14 07:52 UTC, rnd-debug commented
Thx. Should be fixed :)

2020-10-30 08:55 UTC, mindsers commented
This PR seems to be ready. Thanks for your work. I'll merge it! 🚀

2020-10-30 08:57 UTC, mindsers approved these changes
🚀

2020-10-30 08:57 UTC, merged

2020-10-30 10:18 UTC, rnd-debug commented
@mindsers Thank you!